### ISSUE TITLE
Addon is constantly creating new, multiple macros, and removing old ones from my bars.

### ISSUE THREAD

**Issue by UnburdenedInsanity** [JamienAU/RandomHearth#7]
And after this reset (mid-day random reset in EU) my macros are renamed to "Give whispers an instant ...", then I can't see what the last word is because of the Save button.

The macro sometimes disappears from my bars also, so I have to take one of the new ones which it is creating to put there.

**Comment by JamienAU** [comment]
The wording you provided matches WoW Instant Messenger, the text "Give whispers an instant.." doesn't exist in my addon.
As for how it's getting there, that's a strange one. It's possibly because I used "_" instead of "nil" when updating the macro, so I've updated that in r18.

I wasn't able to replicate on my end, so if you could please test and confirm that would be great thanks.
